model_name = "google"
WEB_SEARCH = False
DOC_SEARCH = False
DB_SEARCH = False
session_id = ""
search_method = "Embedding + Qdrant"   
ocr_method = "tesseract"
model_name = "azureai"
webpages_to_include = 3
database = "Vanna_db"
host = "localhost"
port = "5432"
user = "postgres"
password = "Moodle"
db_type = "PostgreSQL"
schema = "Public"
AMO_EMAIL="xxxxxxxx@capgemini.com"
AMO_PASS="xxxxxxxxxxxxx"